# Generated by Django 5.1 on 2026-05-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_name', models.CharField(max_length=100, verbose_name='Tên nhân vật yêu cầu')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Class')),
                ('role', models.CharField(blank=True, max_length=20, verbose_name='Role')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='Đội')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yêu cầu thêm thành viên',
                'verbose_name_plural': 'Yêu cầu thêm thành viên',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('search_name', models.CharField(editable=False, max_length=100, verbose_name='Tên tìm kiếm (không dấu)')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Class')),
                ('role', models.CharField(blank=True, choices=[('tank', 'Tank'), ('healer', 'Healer'), ('dps', 'DPS'), ('support', 'Support'), ('flex', 'Flex')], max_length=20, verbose_name='Role')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='Đội')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': 'Thành viên',
                'indexes': [models.Index(fields=['display_name'], name='attendance__display_5e89d9_idx'), models.Index(fields=['search_name'], name='attendance__search__f7bdf3_idx'), models.Index(fields=['active'], name='attendance__active_395a22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Tham gia'), ('absent', 'Không tham gia'), ('uncertain', 'Chưa chắc'), ('late', 'Đến muộn')], max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('device_id', models.CharField(blank=True, max_length=200, verbose_name='Device ID')),
                ('source', models.CharField(choices=[('web', 'Web (member tự báo)'), ('admin', 'Admin'), ('system', 'Hệ thống')], default='web', max_length=20, verbose_name='Nguồn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.member', verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
            },
        ),
        migrations.CreateModel(
            name='WarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('event_date', models.DateField(verbose_name='Ngày bang chiến')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='Hạn báo danh')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('open', 'Đang mở'), ('closed', 'Đã đóng'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_current', models.BooleanField(default=False, verbose_name='Event hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sự kiện bang chiến',
                'verbose_name_plural': 'Sự kiện bang chiến',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['is_current'], name='attendance__is_curr_bcd787_idx'), models.Index(fields=['status'], name='attendance__status_839ebf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('old_note', models.TextField(blank=True)),
                ('new_note', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=200)),
                ('actor_type', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('system', 'Hệ thống')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.attendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
                ('war_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.warevent')),
            ],
            options={
                'verbose_name': 'Lịch sử điểm danh',
                'verbose_name_plural': 'Lịch sử điểm danh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='war_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.warevent', verbose_name='Sự kiện'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['war_event'], name='attendance__war_eve_3fafc5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('war_event', 'member'), name='unique_attendance_per_event'),
        ),
    ]
