# Generated by Django 6.0.7 on 2026-07-21 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_member_update_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='attendance.member', verbose_name='Thành viên'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='class_name',
            field=models.CharField(blank=True, choices=[('Thiết Y', 'Thiết Y'), ('Huyết Hà', 'Huyết Hà'), ('Toái Mộng', 'Toái Mộng'), ('Thần Tương', 'Thần Tương'), ('Cửu Linh', 'Cửu Linh'), ('Long Ngâm', 'Long Ngâm'), ('Tố Vấn', 'Tố Vấn')], max_length=50, verbose_name='Phái đề xuất'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='class_variant',
            field=models.CharField(blank=True, choices=[('Phá', 'Phá'), ('Ngự', 'Ngự'), ('Thiên Vấn', 'Thiên Vấn'), ('Tố Tâm', 'Tố Tâm')], max_length=50, verbose_name='Hệ/phân nhánh đề xuất'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú của người gửi'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='requested_name',
            field=models.CharField(max_length=100, verbose_name='Tên nhân vật đề xuất'),
        ),
    ]
