# Generated by Django 6.0.7 on 2026-08-10 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='Tên đăng nhập')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Chỉnh sửa'), ('delete', 'Xoá')], max_length=20, verbose_name='Hành động')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Loại đối tượng')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID đối tượng')),
                ('object_repr', models.CharField(blank=True, max_length=250, verbose_name='Đối tượng')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Thay đổi')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Thiết bị/trình duyệt')),
                ('browser_id', models.CharField(blank=True, max_length=64, verbose_name='Mã trình duyệt')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhật ký quản trị',
                'verbose_name_plural': 'Nhật ký quản trị',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='attendance__created_96cb3e_idx'), models.Index(fields=['object_type', 'object_id'], name='attendance__object__31cd4a_idx'), models.Index(fields=['actor_username'], name='attendance__actor_u_75d7e6_idx')],
            },
        ),
    ]
