# Generated by Django 6.0.7 on 2026-08-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_adminactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sử thay đổi điểm danh', 'verbose_name_plural': 'Lịch sử thay đổi điểm danh'},
        ),
    ]
